In [1]:
import numpy as np
import math
with open('data.txt', 'r', encoding='utf-8') as f:
    text = f.read()

In [2]:
print(text[:100])

First Citizen:
Before we proceed any further, hear me speak.

All:
Speak, speak.

First Citizen:
You


In [5]:
def text_split_assist(text):
    comma_splitted = ' '.join(text.split(','))
    newLine_split = ' '.join(comma_splitted.split('\n'))
    # remaining are removing &c, :, --, ', ?, !, ., ;
    colon_split = ' '.join(newLine_split.split(":"))
    double_dash_split = ' '.join(colon_split.split('--'))
    kotation_split = ' '.join(double_dash_split.split("'"))
    question_mark_split = ' '.join(kotation_split.split('?'))
    exclamation_split = ' '.join(question_mark_split.split('!'))
    fullstop_split = ' '.join(exclamation_split.split('.'))
    semiColon_split = ' '.join(fullstop_split.split(';'))
    garbage_removable_split = ' '.join(semiColon_split.split('&C'))
    final_split = ' '.join(garbage_removable_split.split('&c'))
    return final_split

final_split = text_split_assist(text)

total_tokens = sorted(set(list(final_split.split(' '))))
# Adding all the unique necessary elements we removed
unique_elements = [' ',',','.','\n','?','!', "'",':',';','--']
# print(total_tokens[len(total_tokens) - 1])
# to remove '' token
total_tokens.pop(0)
total_tokens = unique_elements + total_tokens
print(total_tokens[:100])

[' ', ',', '.', '\n', '?', '!', "'", ':', ';', '--', '3', 'A', 'ABHORSON', 'ABRAHAM', 'ADRIAN', 'AEacides', 'AEdile', 'AEdiles', 'AEneas', 'AEsop', 'ALL', 'ALONSO', 'ANGELO', 'ANNE', 'ANOTHER', 'ANTIGONUS', 'ANTONIO', 'ARCHBISHOP', 'ARCHIDAMUS', 'ARIEL', 'AUFIDIUS', 'AUMERLE', 'AUTOLYCUS', 'Abase', 'Abate', 'Abated', 'Abbot', 'Abel', 'Abhorred', 'Abhorson', 'Abides', 'Able', 'About', 'Above', 'Abraham', 'Absolute', 'Accept', 'Accomplish', 'According', 'Accords', 'Account', 'Accountant', 'Accursed', 'Accuse', 'Achieve', 'Acquaint', 'Action', 'Adam', 'Add', 'Added', 'Adding', 'Address', 'Adieu', 'Adjudged', 'Admit', 'Adonis', 'Adoptedly', 'Adopts', 'Adrian', 'Adriatic', 'Advance', 'Advantaging', 'Adversity', 'Advertising', 'Advocate', 'Affection', 'Affliction', 'Affrighted', 'Affrights', 'Affront', 'Afore', 'Afresh', 'Afric', 'African', 'After', 'Again', 'Against', 'Agamemnon', 'Age', 'Aged', 'Agenor', 'Agreed', 'Agrippa', 'Ah', 'Aim', 'Aiming', 'Airy', 'Ajax', 'Al', 'Alack']


In [6]:
#very simple tokenizer
clean_text1 = ' '.join(text.split('&C'))
final_text = ' '.join(clean_text1.split('&c'))
# print(final_text[:100])

import re

def encode_text_assist(plain_text):
    pattern = r"(--|[,.\n?!':;\s])"
    plain_text = re.split(pattern, plain_text)
    #joining with spaces
    # plain_text = ' '.join(plain_text)
    #now splitting through spaces
    # plain_text = plain_text.split(' ')
    tokens_arr = []
    for i,t in enumerate(plain_text):
        # print(f't:{t}')
        # t = t.strip()
        if t and t in total_tokens:
            tokens_arr.append(t)
            continue
        else:
            continue

    return tokens_arr

vocab_size = len(total_tokens)
word_to_int = {w:i for i,w in enumerate(total_tokens)}
int_to_word = {i:w for i,w in enumerate(total_tokens)}
# in encode I need to create some function to split up words
encode = lambda l: [word_to_int[w] for w in encode_text_assist(l)]
encode_list = lambda l: [word_to_int[w] for w in l]
decode = lambda l: ''.join([int_to_word[i] for i in l])
print(vocab_size)
print(encode("ANGELO; --"))
print(decode(encode("ANGELO; --")))

13851
[22, 8, 0, 9]
ANGELO; --


In [7]:
# Creating Perceptron/neuron Node, Layer and MLP Class
# class Neuron:
#     def __init__(self,prev_layer,forward_layer,activation,embedding_per_vocab):
#         # self.prev_layer = prev_layer
#         # self.forward_layer = forward_layer 
#         self.activation = activation
#         self.initial_random_w_gen()
#         self.embedding_per_vocab = embedding_per_vocab
        
        

#     # random weight generation for initial setup
#     def initial_random_w_gen(self):
#         self.weight = [self.random_param_gen() for _ in range(self.embedding_per_vocab)]

#     # Instead of creating bias per neuron, we will create biases arrays per layer, which just makes life easier working with matrix operations
#     # adding biases to the final mat mul of weights and input values
#     # def initial_bias_gen(self):
#     #     self.bias = self.random_param_gen()
        
#     def random_param_gen(self,range = 8):
#         return np.random.uniform(-range,range)

#     def apply_relu(self,val):
#         # relu simply means, if negative or zero, the value is 0 and if positive, y = x
#         np.maximum(0,val)

#     def forward_pass(self):
#         pass

    

In [8]:
#putting softmax on global scope, as it is used in many clases
# def temperature_scaled_softmax(logits, T=1.0):
#     logits = np.array(logits)  # Ensure it's a NumPy array
#     scaled_logits = logits / T  # Apply temperature scaling
#     exp_values = np.exp(scaled_logits - np.max(scaled_logits))  # Stability trick
#     return exp_values / np.sum(exp_values)

def softmax(x, dtype=np.float32):
    # """Numerically stable softmax with float32 or float64 support."""
    x = np.asarray(x, dtype=dtype)  # Ensure correct dtype
    x_max = np.max(x, axis=-1, keepdims=True)  # Stability trick
    exp_x = np.exp(x - x_max, dtype=dtype)  # Compute exp with correct dtype
    print(f'softmax_valllll:{np.sum(exp_x, axis=-1, keepdims=True, dtype=dtype)}')
    return exp_x / np.sum(exp_x, axis=-1, keepdims=True, dtype=dtype)

    # I need to use adaptive scaling strategy, where I initially use average probaility measuring technique and when the output variation increases more
    # I will opt to using real softmax
    #Normalizing negative values to 0 by adding smallest value positive alternate to zero down
    
    # smallest_element = abs(min(x)) # abs to convert to absoulte positive value
    # equalizing_negative_val = x + np.array([smallest_element])
    # sum_val = np.sum(equalizing_negative_val, axis=0)
    # normalized_val = np.array(equalizing_negative_val / sum_val, dtype=dtype)
    # return normalized_val

    # return temperature_scaled_softmax(x,100)

class Layer:
    def __init__(self, nodes_num,embedding_per_vocab=None, bias = True,prev_layer = None, forward_layer = None,activation = 'relu',type='hidden'):
        self.nodes_num = nodes_num
        self.bias = bias
        self.activation = activation
        self.prev_layer = prev_layer
        self.forward_layer = forward_layer
        self.type = type
        # self.bias = bias
        self.embedding_per_vocab = embedding_per_vocab
        # We could choose some layer without any bias
        if bias:
            self.initial_bias_gen(range=2)
        else:
            self.bias = None
        self.create()

    def initial_bias_gen(self,range):
        self.biases = self.__gen_random_numbers(self.nodes_num,range)
    
    def __gen_random_numbers(self,size,range):
        #not the best way, but it works starting out with any random number
        # return range * np.random.rand(size)
        # so, we use something better like:
        return np.random.uniform(-range,range,size=size)

    def apply_relu(self,val):
        # relu simply means, if negative or zero, the value is 0 and if positive, y = x
        np.maximum(0,val)
    
    def create(self):
        # Instead of explicitly Making another Neuron class and creating segmentation
        # I would use the better option to create matrix of weights per node per layer, and also, simd is just better usable this way
        # self.nodes = [Neuron(self.prev_layer,self.forward_layer,self.activation,embedding_per_vocab=self.embedding_per_vocab) for _ in range(self.nodes_num)]
        self.nodes = [self.__gen_random_numbers(self.embedding_per_vocab,range=8) for _ in range(self.nodes_num)] if self.type == 'input' else [
            self.__gen_random_numbers(self.prev_layer.nodes_num,range=8) for _ in range(self.nodes_num)]

    # Receive the data processed by previuos MLP layer or if the layer is first, receives the output from mskd-self-attention layer
    def forward_pass(self,input_arr):
        element_wise_weight_mmul = np.array(self.nodes) * np.array([input_arr])
        mmul_val_addition = np.sum(element_wise_weight_mmul, axis=1)
        if(self.bias == None):
            return mmul_val_addition
        else:
            bias_addition = np.array(mmul_val_addition) + np.array(self.biases)
            # return processed vale with weights and input arr
            return bias_addition
        

In [13]:
class MLP:
    def __init__(self, layers_num, nodes_per_layer,embedding_per_vocab,custom_layer_config={}):
        self.layers_num = layers_num
        self.nodes_per_layer = nodes_per_layer
        self.embedding_per_vocab = embedding_per_vocab
        self.mlp_allLayers_values = []
        self.initiate()

    # def initiate(self):
    #     self.head = Layer(self.nodes_per_layer,embedding_per_vocab=self.embedding_per_vocab)
    #     current_layer = self.head
    #     for _ in range(self.layers_num - 1):
    #         new_layer = Layer(nodes_num=self.nodes_per_layer)
    #         current_layer.forward_layer = new_layer
    #         new_layer.prev_layer = current_layer
    #         current_layer = new_layer

    # In future we are going to create matrix for weights of each layer and each neuron inside it, which will be better approach then using linked-lst
    # style linking layers.
    def initiate(self):
        #this is the array implementation of layers and neurons mapping, which is better than using above lnkd-lst method
        # we did if else here because in the layer class, we need to be able to distinguish between layer types and position
        # to assign specific weights shape
        # self.layers = [Layer(nodes_num=self.nodes_per_layer,embedding_per_vocab=self.embedding_per_vocab,type='input') if i==0 else
        #                Layer(nodes_num=self.nodes_per_layer,embedding_per_vocab=self.embedding_per_vocab,prev_layer=self.layers[i-1])
        #                for i in range(self.layers_num)]

        # self.layers = [Layer(nodes_num=self.nodes_per_layer,embedding_per_vocab=self.embedding_per_vocab,prev_layer=self.layers[i-1])
        #                for _ in range(self.layers_num)]
        
        # self.layers[0] = Layer(nodes_num=self.nodes_per_layer,embedding_per_vocab=self.embedding_per_vocab,type='input')

        # Neither of above way worked as, self.layers[i - 1] couldn't be assigned sooo...
        self.layers = []
        for i in range(self.layers_num):
            if i == 0:
                self.layers.append(Layer(nodes_num=self.nodes_per_layer,embedding_per_vocab=self.embedding_per_vocab,type='input'))
            else:
                self.layers.append(Layer(nodes_num=self.nodes_per_layer,embedding_per_vocab=self.embedding_per_vocab,prev_layer=self.layers[i-1]))
        
    # here we will attach the self attention masking layer
    ## Or not, cause we could just use model class to indirectly create propagation between MLP and self attention layers or any
    # def attach_to_head(self, attention_layer):
            
    def feed_forward(self,masked_self_attn_embedd_arr):

        # Removing any data that existed before
        # I opted to keep data according to data processed in matrix form
        # making easier for final averaging gradient on position basis
        self.mlp_allLayers_values = []
        
        #Now element wise matrix mul with weights of neurons in layer and mskd_self_attn_embedd_arr val, one layer at a time, and
        # also adding bias at the end of neuron wise mat mul
        data_to_process = masked_self_attn_embedd_arr
        for layer in self.layers:
            # this add all the values output from slef-attn layer output adjacent input to second-last layer, as at last layer the loop ends
            self.mlp_allLayers_values.append(data_to_process)
            data_to_process = layer.forward_pass(data_to_process)

        # Adding last layer or the layer before normalization layer
        self.mlp_allLayers_values.append(data_to_process)
        # print(f'length of values assigned to corresponding layer::{len(self.mlp_allLayers_values)}')
        # returns the arr after getting operated through all MLP layers
        # now Model class will pass this return value to normalizer for getting probability distribution out of it
        return data_to_process, self.mlp_allLayers_values
        
        
# layer = Layer(10)
# for n in layer.nodes:
#     print(f'n.weight: {n.weight}')
#     print(f'n.bias: {n.bias}\n')



In [15]:
class MaskedSelfAttLayer:
    def __init__(self,context_len=8,initial_base_f =20,positional_function_f_change = 1.5,embedding_len_per_vocab = 2):
        self.context_len = context_len
        # it will look like: [ [[query final value],[key final value],[value final value],[embedding at the last, that is after adding self-attn value]],
        #[---same as before---], [---same as before---] ]
        self.context_history = {}
        # this means, for vector, each index gets uplift of 30, like 30, 60, 90, as f increases like x2, it will increase to 60, 120, 180 and so on
        self.base_frequency = initial_base_f 
        self.frequency_change_rate = positional_function_f_change
        self.embedding_per_vocab = embedding_len_per_vocab
        self.gen_first_weights()
        self.gen_initial_query_key_value_w()
    
    #start input propagation
    def start_input_prop(self,data,mode='train'):
        # In train mode, we need to train the layers for guessing every next token,
        # but in trained model, we only use other token to get masked self-attention value for very last token, and then run through MLP
        inference_len = len(data)
        # we say inference_len because we will always get complete 8 tokens for training
        data_np = np.array([data])
        # eg [[1,2],[3,4]] * [3,4] = [[3,8],[9,16]]
        initial_values = np.array(self.first_weights) * data_np
        # Adding positional encodings, sine cosine alternating function values
        self.setup_main_self_attn_work(initial_values)
        
    def setup_main_self_attn_work(self,init_values):
        # Here we itteratively create context_len values and then try to train the MLP layer # I am still tinkering so, might not be correct
        for i in range(self.context_len):
            #setting up positional encoding(means adding pos. encoding for every context_len vals)
            for j in range (self.embedding_per_vocab):
                # so essentially i is token number and j is the embedding number
                # we did i+1 and j+1 cause, the alternating function takes position that starts with 1 not 0 like indexing in code
                init_values[i][j] += self.alternating_sine_cosine_p_value(i+1, j+1)
        # after adding positional_values
        self.after_positional_values = init_values
        # now multiplying to get query, key and values parameter context wise value
        self.context_history['query'] = self.after_positional_values * np.array(self.query_weights)
        self.context_history['key'] = self.after_positional_values * np.array(self.key_weights)
        self.context_history['value'] = self.after_positional_values * np.array(self.value_weights)
            

    #generate initial weight for the very first layer of weights for inputs, we are only using two size vector for data representation
    #with weights for each context_len assigned value, means each vector contains context_len(default 8) weights
    def gen_first_weights(self):
        self.first_weights = [self.__gen_random_numbers(self.context_len) for _ in range(self.embedding_per_vocab)]
        
        
    #generate initial random query, key and value weights
    def gen_initial_query_key_value_w(self):
        # initializing the weights for Q,K and V
        #For multi-head, I don't understand that completely now, but we will come back to it
        # self.query_weights = [self.__gen_random_numbers(self.embedding_per_vocab) for _ in range(self.context_len)]
        # self.key_weights = [self.__gen_random_numbers(self.embedding_per_vocab) for _ in range(self.context_len)]
        # self.value_weights = [self.__gen_random_numbers(self.embedding_per_vocab) for _ in range(self.context_len)]

        # For sigle head self-attn layer
        self.query_weights = [self.__gen_random_numbers(self.embedding_per_vocab)]
        self.key_weights = [self.__gen_random_numbers(self.embedding_per_vocab)]
        self.value_weights = [self.__gen_random_numbers(self.embedding_per_vocab)]
        

    def __gen_random_numbers(self,size):
        #not the best way, but it works starting out with any random number
        return 2 * np.random.rand(size)

    #We need alternating sine cosine position value for each token, but as the frequency increase per couple and need for specific number of couples are
    #dependent upon the size of network, we need to set that up
    def alternating_sine_cosine_p_value(self,token_position,vector_position):
        # token position is like 2 in hello there for there
        # vector position is the position of value in first index of first token value
        couple_number = math.ceil(vector_position / 2)
        # we do (couple_number -1) * frequency change rate, because we don't just multiply by couple number, we have a set frequency increase rate
        relative_f_change = couple_number if couple_number == 1 else (couple_number - 1) * self.frequency_change_rate
        # we alternate between sine and cosine periodically
        sine_or_cosine = 'sine' if vector_position % 2 == 0 else 'cosine'
        if sine_or_cosine == 'sine':
            return np.sin(np.radians(token_position * (self.base_frequency * relative_f_change)))
        else: 
            return np.cos(np.radians(token_position * (self.base_frequency * relative_f_change)))
            
    # As the q, k, and v might be needed to be remembered migh as well use MLP class here to give the final matrix
    # which should be normalized by passing through final linear layer and get probability distribution
    # I don't know the exact way I am going to do, we will tinker and see what works best
    # what I am doing here is sending back the whole batch initial embedd ready to be trained one array at a time
    def batch_feed_forward_data_ready(self,token_input_arr):
        # Passing whole single batch data, means matrix of shape (batch_size * context_len) 
        # so, weights of every array of batch, multiplies with corresponding weight index/number all at once
        token_input_arr = np.array(token_input_arr)[:,np.newaxis,:] * np.array(self.first_weights) # here first_weights are broadcasted to each batch_arr
        token_input_arr = token_input_arr.transpose(0,2,1) # we are trying to keep embedding of one voab in single array stream
        return token_input_arr

In [179]:
# This will be the class we would use, which wraps all inner workings with all the previous classes
class Model:
    def __init__(self,context_len,training_batch_number=None,embedding_len_per_vocab=2):
        self.context_len = context_len
        self.embedding_per_vocab = embedding_len_per_vocab
        self.training_batch_number = training_batch_number
        self.attention_layer = MaskedSelfAttLayer(context_len=self.context_len,embedding_len_per_vocab=2)
        self.mlp = MLP(nodes_per_layer=12,layers_num=6,embedding_per_vocab=self.embedding_per_vocab)
        # Will have error per batch
        self.err_per_batch_tokens =  np.zeros(vocab_size)
        self.mlp_all_layers_values = []
        # This final normalizing layer is used to decrease the parameters of the whole network, rather we use cont_len nodes at the final_layer
        # which was incorrect, because we need to create probability distribution over all the possible tokens 
        # so, final layer will have len(total_tokens) which is vocab_size
        self.final_normalizing_layer = Layer(nodes_num=vocab_size,bias=False,prev_layer=self.mlp.layers[self.mlp.layers_num - 1])


    def negative_log_loss_penalty(self,ground_truth,predicted_value):
        lower_limit = 0.0000001
        arr = np.clip(predicted_value,lower_limit, 1-lower_limit)
        neumerator = arr - ground_truth
        denominator = arr * (np.ones(vocab_size) -  arr)
        return neumerator / denominator
        


    # Need to create Gradient descent values for all of these layers
    # calculating the value change that would propagate from each node to the final output, and how changes in input change final output
    def backpropagation(self):
        #calculate gradient for each layer by muliplying a from last layer to first a being a * w + b = f(x)
        self.gradient_last_to_first_layer = []

        # Now reversing the values of layers as we are calculating gradient from last to first
        # from normalized layer to first layer
        reversed_layerWise_values = self.average_per_layers_value[::-1]# clipped the last value

        # print(reversed_layerWise_values)
        # we leave the last layer value as it is only useful for getting the expected answer and penalty
        # In backprop we only use values from second last layer
        layers_reversed = self.mlp.layers[::-1]

        # This is wrong, every node has different gradient
        # Now revising the approach
        for i,values_row in enumerate(reversed_layerWise_values):
            # print(f'values_row::{reversed_layerWise_values}')
            # here we do upto second layer as we don't need first layer values, as the first layer value is just output from
            # self-attention layer
            if i == 0:
                self.gradient_last_to_first_layer.append(values_row)
            else:
                # gradient_last_to_first_layer[i-1] * values_row * numnber of nodes in layer before this
                
                # This is the wrong approach
                # self.gradient_last_to_first_layer.append(self.gradient_last_to_first_layer[i-1] * values_row * layers_reversed[i - 1].nodes_num)

                # Now improving to correct one

                for index,val in enumerate(self.gradient_last_to_first_layer[i - 1]):
                    self.gradient_last_to_first_layer.append(values_row * val * layers_reversed[i - 1].nodes_num)


        # In this matrix first value of gradient is just for the extra nmormalized layer and all the other 72 array in base model is for
        # other nodes in the MLP layers, every nodes weight with different/unique gradient
        
        print(f'gradients::::{self.gradient_last_to_first_layer}')
        print(f'length of gradients::{len(self.gradient_last_to_first_layer)}')
        # print(f'first_scaled_layer_grad::{self.first_scaled_layer_grad}')


    # Update weight and biases, right now I am just updating weights, we will see about biases update later
    def gradient_descent(self):


        # Also print overall mean squared erro value here
        pass
    
    # Creating a abstraction out of train, just to make code more readable and managable
    def train_per_batch_arr(self,arr_data, expected_output):
        self.attention_layer.setup_main_self_attn_work(arr_data)
        batch_single_arr_after_norm = []
        # Now everything is setup, now we need to serially go over token embeddings and multiply query with previous tokens key and create a softmax
        # between its query key product value and other previous tokens value and aggregate to create final masked self attn-value
        for i,_ in enumerate(arr_data):
            

            if(i == 0):
                data_through_mlp, values_across_layers = self.mlp.feed_forward(self.attention_layer.context_history['value'][i]) # where i is always 0 in this situation
            else:
                # [:(i + 1)] because slicing is exclusive operation that leaves last index
                query_key_mmul = np.array(self.attention_layer.context_history['query'][i]) * np.array(self.attention_layer.context_history['key'][:(i+1)])
                # now adding each array into single number. eg:- [q2*k1 + q2*k1,q2*k2,q2*k2]
                # By the way q2 is different in every instance like k1 and k2, i am just signifying the arr data relating to specific cont_len vocab
                
                # print(f'query_key_mmul:{query_key_mmul}')
                softmax_ready_digits = np.sum(query_key_mmul,axis=1) # By the way axis=1 means adding row not column, 0 means column
                # Now perform softmax
                # print(f'sofmax_ready_digit::{softmax_ready_digits}\n')
                through_softmax = softmax(softmax_ready_digits)
                # Now multiplying sofmax value corresonding to value of each cont_len vocab and add according to corresponding index
                # print(f'values::{self.attention_layer.context_history['value'][:i+1]}\n th_smax::{through_softmax[:,np.newaxis]}')
                value_through_contx = self.attention_layer.context_history['value'][:i+1] * through_softmax[:,np.newaxis]# broadcasing through all array
                final_summed_val = np.sum(value_through_contx, axis=0) # axis=1 because we need to add all vector embedding through corresponding index
                # passing through MLP Network
                data_through_mlp, values_across_layers = self.mlp.feed_forward(final_summed_val)

            # Now passing through final_normalizing layer and push to batch_single_arr_after_norm arr and return back to train to delegate to some
            # abstraction to handle remaining work
            final_data = self.final_normalizing_layer.forward_pass(data_through_mlp)
            # Also puhsing values across layers into self.mlp_allLayers_value so, that we could calculate average gradient per position and
            # also pass through update chain to take multiple data units into consideration with average penalty
            self.mlp_all_layers_values.append(values_across_layers)
            # print(f'final_data_before_softmax::{final_data}\n')
            output_data = softmax(final_data)
            
                    
            
            # print(f'final_data:{final_data}\n')
            # print(f'first_index_val::{final_data[0]}')
            batch_single_arr_after_norm.append(output_data)


        # We will first calculate the negative log error for each value and then, average them all in a single dim array

        for i,arr in enumerate(batch_single_arr_after_norm):
            #Create a single dim array with zero initialized array of size vocab_size as we copare to ground_truth and predicted truth
            zeros_arr = np.zeros(vocab_size)
            # print(f'expected_output[i]__i::{len(arr)}\n')
            # print(f'expected_output[i]::{len(expected_output)}\n')
            zeros_arr[expected_output[i]] = 1

            # Now Zeros_arr is the ground truth data arr and arr is predicted data arr, now we need to calculate negative log error for
            # for each position
            self.err_per_batch_tokens += self.negative_log_loss_penalty(zeros_arr,arr)
            
            # for j, GT in enumerate(zeros_arr):
            #     self.err_per_batch_tokens[j] += self.negative_log_loss_penalty(GT, arr[j])

        
        # finally return all the batch_single array prediction through softmax

        
        # print(f'values_per layers in arr 8, len::{len(self.mlp_all_layers_values)}')
        return batch_single_arr_after_norm
            
        
    
    # batch data and their respective expected output
    def train(self,batch_data, batch_e_output,lr=0.001):
        self.err_per_batch_tokens = np.zeros(vocab_size)
        self.mlp_all_layers_values = []
        batch_final_after_softmax = []
        batch_predicted_token = []
        batch_predicted_token_prob = []
        batch_complete_data =self.attention_layer.batch_feed_forward_data_ready(batch_data)
        # Now we loop through train_per_batch_arr as function name suggests, and finally get normalized data arr with probability distribution
        for i,data in enumerate(batch_complete_data):
            train_per_batch_val = self.train_per_batch_arr(data, batch_e_output[i])
            for el in train_per_batch_val:
                batch_predicted_token.append(np.argmax(el))
                batch_predicted_token_prob.append(el[np.argmax(el)])
            batch_final_after_softmax += train_per_batch_val

        # dividing self.err_per_batch_tokens the number i.e. context_len * batch_size 

        self.err_per_batch_tokens /= (self.context_len * self.training_batch_number)

        # Now averaging all the a value per layer, throughout the whole training process including normalizing layer
        # print(f"self.mlp_allLayers_value::{len(self.mlp_all_layers_values[0][1])}")
        
        ############## np.sum does not work for heterogeneous size, so need to use good old loop addition 
        # self.mlp_all_layers_values = np.sum(self.mlp_all_layers_values,axis=0)
        
        # Average all samples of value per layer
        # it's more like sum of all itterations, cause we haven't divided by total number of itteration count, those beong
        # context_len * batch_number
        self.average_per_layers_value = []
        
        for i in range(self.mlp.layers_num + 1):
            # Creates zeros array of length equal to the specific layer value length
            average_one_layer = np.zeros(len(self.mlp_all_layers_values[0][i]))
            for j in range(len(self.mlp_all_layers_values)):
                # here we loop through samples number so, j at start and i specifies the layer we are targeting
                average_one_layer += self.mlp_all_layers_values[j][i]

            average_one_layer /= self.context_len * self.training_batch_number
            self.average_per_layers_value.append(average_one_layer)

        # print(f'len of averaged up values array:::{len(self.average_per_layers_value)}\n')
        # print(f'len of all layers values:::::{len(self.mlp_all_layers_values)}')
        # print(f'len of sel.err len:::::{len(self.err_per_batch_tokens)}')

        # setting up error for layers other than normalization layer
        self.mlp_error_val = np.sum(self.err_per_batch_tokens, axis=0)

        print(f'the final mlp error value:::{self.mlp_error_val}')
        
        print(batch_predicted_token)
        print(f'predicted_token_prob:{batch_predicted_token_prob}\n')
        print(f'Error_final::{self.err_per_batch_tokens}')
        # print(batch_final_after_softmax)

        self.backpropagation()
        self.gradient_descent()

In [19]:
#Create batches of training and validation data and also seperate test data, as we donot want the model to remeber, rather
#learn patterns
encode_ready_tokens = encode_text_assist(final_text)
ready_tokens_len = len(encode_ready_tokens) 
train_text = encode_ready_tokens[:int(ready_tokens_len * 0.9)]
validation_text = encode_ready_tokens[int(ready_tokens_len * 0.9):]

In [173]:
# print(encode_ready_tokens[:100])
batch_size = 4
def create_batches(context_len,number_of_batches):
    #8 being context_len and we actually randint(0,len(final_text) - context_len + 1) if randint were inclusive but it's not so fine with,
    # - context_len+1 as for eg randint(0,8) will give value up to 7 
    # np.random.randint(0,len(final_text) - 8, size=4)
    random_pick = np.random.randint(0,len(train_text) - context_len,size=number_of_batches)
    train_data_batch = [encode_list(train_text[i:i+context_len]) for i in random_pick]
    test_data_batch = [encode_list(train_text[i+1:i+context_len+1]) for i in random_pick]
    
    #return training_data, and each subsequent output as expected prediction,eg:
    # train_data_batch = [[1,2,3,4,5],[---]], and xb = [[2,3,4,5,6],[---]], so here context_len is 5 and each index in xa would have it's expected 
    #output in xb
    return train_data_batch, test_data_batch

# This data kinda suck, while having a shorter context-len like 8, so, increased to 12
model = Model(12,4)

for _ in range(1):
    train_data, expected_prediction = create_batches(model.context_len,model.training_batch_number)
    model.train(train_data,expected_prediction,lr=0.1)


the final mlp error value:::13849.006648468785
[8624, 8624, 8624, 8624, 8624, 8624, 8624, 8624, 2323, 5529, 5414, 5414, 8624, 8624, 8624, 8624, 8624, 8624, 8624, 8624, 8624, 5529, 8624, 8624, 4559, 8624, 8624, 8624, 8624, 8624, 5414, 8624, 5414, 5529, 8624, 5529, 4559, 8624, 8624, 8624, 8624, 8624, 8624, 5414, 5414, 5414, 5414, 5414]
predicted_token_prob:[1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]

Error_final::[-3.33333267e+06 -6.24999062e+05 -4.16665708e+05 ...  1.00000010e+00
  1.00000010e+00  1.00000010e+00]
gradients::::[array([ 4.99499761e+10,  2.69481061e+10,  4.64174648e+10,  2.48761000e+10,
        3.81283951e+10, -6.26657665e+10,  1.47021325e+11,  1.17727477e+10,
       -4.40464674e+10, -3.42771093e+10, -4.43181434e+10,  3.85161028e+09]), array([-2.56025143e+21, -2.37888601e+21, -2.

In [21]:
A = np.array([[1, 2], [2, 3], [3, 4]])
B = np.array([[1, 2], [1, 3]])

result = A[:, np.newaxis, :] * B  # Broadcasting
print(result)
print(result.transpose(0,2,1))

def softmax(x):
    exp_x = np.exp(x - np.max(x))  # Subtract max(x) for numerical stability
    return exp_x / np.sum(exp_x)

# Example usage:
x = np.array([2.0, 1.0, 0.1])
softmax_values = softmax(x)
print(softmax_values)


a = np.array([1, 2, 3, 4])  # Shape: (4,)
b = np.array([[1, 2, 3, 4],  # Shape: (4, N)
              [1, 2, 3, 4],  
              [1, 2, 3, 4],  
              [1, 2, 3, 4]])

result = b * a[:, np.newaxis]  # Expanding `a` to (4, 1) and broadcasting
# print(result)

# print(b * np.array([[1],[2],[3],[4]])) # same as what we did before with np.newaxis

print([[1],[2],[3]] + [[4],[5]])

a = np.array([[1.13645561e-02, 1.52903492e-02],
 [4.53067962e+01, 6.55301006e+01],
 [6.57354624e-03, 1.17096469e-01]])
np.sum(a,axis=1)
print(np.array([1,2,3,4,5]) + np.array([abs(-1)]))

x = np.array([1000, 1001, 1002])
x_max = np.max(x, axis=-1, keepdims=True)  # Find max value (1002)
x_stable = x - x_max  # Subtract 1002 from all elements → [-2, -1, 0]

exp_x = np.exp(x_stable)  # Now, exp(x_stable) = [e^(-2), e^(-1), e^0]
# softmax = exp_x / np.sum(exp_x)
# print(softmax)  # Outputs stable probabilities

def log_softmax(x, dtype=np.float32):
    x = np.asarray(x, dtype=dtype)
    x_max = np.max(x, axis=-1, keepdims=True)
    log_sum_exp = np.log(np.sum(np.exp(x - x_max), axis=-1, keepdims=True))
    return x - x_max - log_sum_exp

print(f'log_softmax::{log_softmax(np.array([1000, 1, -1000]))}')

def negative_loss_loss_penalty(ground_truth,predicted_value):
        lowest_possible_value = 0.00000001
        clipped_val = np.clip(predicted_value, lowest_possible_value, 1-lowest_possible_value)
        return (clipped_val - ground_truth)/(clipped_val * (1 - clipped_val))

print(negative_loss_loss_penalty(1,0))


arr = np.array([[[1,2],[2,2],[3,2]], 
                [[1,2],[1,2],[1,2]], 
                [[1,2],[1,2],[1,2]]])

result = np.sum(arr, axis=0)

print(result)

[[[ 1  4]
  [ 1  6]]

 [[ 2  6]
  [ 2  9]]

 [[ 3  8]
  [ 3 12]]]
[[[ 1  1]
  [ 4  6]]

 [[ 2  2]
  [ 6  9]]

 [[ 3  3]
  [ 8 12]]]
[0.65900114 0.24243297 0.09856589]
[[1], [2], [3], [4], [5]]
[2 3 4 5 6]
log_softmax::[    0.  -999. -2000.]
-100000000.0
[[3 6]
 [4 6]
 [5 6]]
